### PR TITLE
add Plato to control project average maintainability

### PR DESCRIPTION
**Pull request by julien-leroy**
There is probably some things to improve and correct, I have faith in you ;)

### CODE REVIEW

**Comment by FGRibreau** [comment]
Hello julien :)

You need to use:

```javascript
var cli = require('plato/lib/cli');
cli.exec({
args:{files: options.args}
}, function () {
  console.log('Done!');
});
```

instead of

```javascript
 var cmd = 'plato -r -d node_modules/plato/report ' + p.resolve(__dirname);
```

because plato is **not** installed globally. Forward to `option` the -r (`options.args.r`))and the -d (`options.d.value`) too. 

See https://github.com/es-analysis/plato/blob/master/lib/cli.js#L14

**Comment by julien-leroy** [comment]
All right ! ;)

FG is smart

**Comment by FGRibreau** [comment]
thanks-thank-you

**Comment by valeriansaliou** [comment]
+1 for this one. Eager to work on fixes so that it merges and integrate w/ latest commits, if help needed.

**Comment by FGRibreau** [comment]
@valeriansaliou that would be AWESOME! @julien-leroy stopped working on it so you can take the lead!

**Comment by valeriansaliou** [comment]
Great, let's do that. I'll follow up later in the WE w/ a MR. Cheers!

**Comment by valeriansaliou** [comment]
Merged this PR w/ newer changes and improved the way check-build handles Plato in #42

**Comment by FGRibreau** [comment]
Duplicate with #43

**Pull request closed without merging**
